### ISSUE TITLE
Maybe a git sync issue?

### ISSUE THREAD

**Issue by DagnyJay** [micahwierenga/sei-cc-7-project-3-issues#2]
**Describe the issue.**
I did ` get fetch --all` and then `git reset --hard origin/master` and it pulled the changes I wanted, but it also kept an empty directory I created. Bahram says I might not have the most up to date version. That's all we got. 

**Paste any relevant code and/or errors (use triple backticks before and after to format as code).**
None - B just says something might be wonky. 

**Paste links to any resources you've consulted for help.**
The git work flow cheat sheet

**Describe your attempt(s) at resolving the issue.**
I don't know if there IS an issue.

**Comment by micahwierenga** [comment]
Git doesn't necessarily track empty directories, but it's only focused on content. And, until a folder has files inside, it doesn't have content.

https://stackoverflow.com/questions/3030230/does-git-ignore-empty-folders
